name: Build and Upload .NET Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Publish self-contained single file
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-win-x64
          path: |
            **/bin/Release/net*/win-x64/publish/**
